#include <iostream>
#include <stdlib.h>
#include <windows.h>
#include <string>
#include <stdio.h>
#include <conio.h>
#include <iomanip>
#include <Windows.h>
#include <algorithm>
#include <math.h>
#include <fstream>
#include <vector>
#include <cstdlib>
#include <ctime> 
#include <vector>
#include <sstream>
